/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teskasir;

import java.text.SimpleDateFormat;
import java.util.Calendar;
/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
    String pilihan="";
    int harga_brg;
    int banyak,jumlah,total,harga,kembali;
    //Membuat object dengan nama n dari class Tabel (Instansiasi)
    Tabel n = new Tabel();
    /**
     * Creates new form NewJFrame
     */
    //method bawaan
    public NewJFrame() {
        initComponents();
    }
    //membuat method untuk menampilkan
    public void tampil(){
        //memberi value pada masaing masing variabel di textfield bernama txtTanggal dst.
        txtTanggal.setText("");
        txtNamaBrg.setText("");
        comboPilih.setSelectedItem("");
        txthargaBarang.setText("");
        txtJumlah.setText("");
        txtHargaTotal.setText("");
        txtBayar.setText("");
        txtKembalian.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txthargaBarang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHargaTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        btnHarga = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        comboPilih = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNamaBrg = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnTgl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Kasir");

        jLabel1.setText("Harga");

        txthargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaBarangActionPerformed(evt);
            }
        });

        jLabel2.setText("Satuan");

        jLabel3.setText("Total");

        jLabel4.setText("Tunai");

        jLabel5.setText("Kembali");

        btnHarga.setText("Hitung Harga");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembalian");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        comboPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", " " }));
        comboPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPilihActionPerformed(evt);
            }
        });

        jLabel6.setText("Kode Barang");

        jTable1.setModel(n);
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Tanggal");

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Barang");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 242, 242));
        jLabel13.setText("Toko Elektronik");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnTgl.setText("Set Tanggal");
        btnTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTglActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                                            .addComponent(txtBayar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHargaTotal, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSimpan)
                                            .addComponent(btnHarga)
                                            .addComponent(btnKembali)))
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txthargaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNamaBrg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnTgl)))
                        .addGap(254, 254, 254))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTgl))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txthargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHargaTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarga, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//pilihan kode barang
    private void comboPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPilihActionPerformed
        // TODO add your handling code here:
        pilihan=(String)comboPilih.getSelectedItem();
        //pilihan kode dibuat dengan switch case 
        switch (pilihan){
            case "01":
                txtNamaBrg.setText("Laptop");
                harga_brg=10000000;
            break;
                //pada case 1, case yang dipilih, variabel txtNamaBrg akan diisi value dengan masing masing value di casenya
                //dengan nama barang laptop pada pilihan pertama
                //dengan harga barang 10.000.000
                //jika kondisi sudah terpenuhi maka coding berhenti
            case "02":
                txtNamaBrg.setText("Mouse");
                harga_brg=100000;
            break;
            //pada case 2, case yang dipilih, variabel txtNamaBrg akan diisi value dengan masing masing value di casenya
                //dengan nama barang Mouse pada pilihan kedua
                //dengan harga barang 100.000
                //jika kondisi sudah terpenuhi maka coding berhenti
            case "03":
                txtNamaBrg.setText("Keyboard");
                harga_brg=200000;
            break;
            //pada case 3, case yang dipilih, variabel txtNamaBrg akan diisi value dengan masing masing value di casenya
                //dengan nama barang Keyboard pada pilihan ketiga
                //dengan harga barang 200.000
                //jika kondisi sudah terpenuhi maka coding berhenti
            case "04":
                txtNamaBrg.setText("Charger");
                harga_brg=100000;
            break;
            //pada case 4, case yang dipilih, variabel txtNamaBrg akan diisi value dengan masing masing value di casenya
                //dengan nama barang Charger pada pilihan keempat
                //dengan harga barang 100.000
                //jika kondisi sudah terpenuhi maka coding berhenti
            case "05":
                txtNamaBrg.setText("Flashdisk");
                harga_brg=45000;
            break;
            //pada case 5, case yang dipilih, variabel txtNamaBrg akan diisi value dengan masing masing value di casenya
                //dengan nama barang Flashdisk pada pilihan kelima
                //dengan harga barang 45.000
                //jika kondisi sudah terpenuhi maka coding berhenti
            case "06":
                txtNamaBrg.setText("Speaker");
                harga_brg=500000;
            break;
            //pada case 6, case yang dipilih, variabel txtNamaBrg akan diisi value dengan masing masing value di casenya
                //dengan nama barang speaker pada pilihan keenam
                //dengan harga barang 500.000
                //jika kondisi sudah terpenuhi maka coding berhenti
            case "07":
                txtNamaBrg.setText("Monitor");
                harga_brg=1000000;
            break;
            //pada case 3, case yang dipilih, variabel txtNamaBrg akan diisi value dengan masing masing value di casenya
                //dengan nama barang Monitor pada pilihan ketujuh
                //dengan harga barang 1.000.000
                //jika kondisi sudah terpenuhi maka coding berhenti
        }
        txthargaBarang.setText(""+Integer.toString(harga_brg));
        //pada variabel txthargaBarang, valuenya akan terisi sesuai saat salah satu case dipilih
    }//GEN-LAST:event_comboPilihActionPerformed
//hitung harga total
    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        // TODO add your handling code here:
        harga = Integer.parseInt(txthargaBarang.getText());
        banyak=Integer.parseInt(txtJumlah.getText());
        jumlah=harga*banyak;
        txtHargaTotal.setText(Integer.toString(jumlah));
        //membuat action dari button harga atau hitung harga
        //variable harga mengambil data txthargaBarang  dan mengubah dari value string ke interger untuk proses selanjutnya
        //variable banyak mengambil data txtJumlah dan mengubah dari value string ke interger untuk proses selanjutnya
        //variable jumlah membuat hasil perkalian dari harga dengan banyak
        //dari text box txtHargaTotal menampilkan hasil dari variable jumlah
    }//GEN-LAST:event_btnHargaActionPerformed
//hitung kembalian
    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        int kembali=Integer.parseInt(txtBayar.getText());
        int total=kembali-jumlah;
        txtKembalian.setText("Rp"+Integer.toString(total));
        //membuat varible kembali lalu mengambil data dari text box txtBayar yang telah di rubah dari value string ke interger
        //membuat variable total lalu melakukan proses pengurangan data kembali dengan jumlah
        //akan menampilkan data total ke text box txtKembalian 
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Transaksi t = new Transaksi(txtTanggal.getText(),txtNamaBrg.getText(),
                txthargaBarang.getText(),txtJumlah.getText(),txtHargaTotal.getText(),
                txtBayar.getText(),txtKembalian.getText());
        n.add(t);
        tampil();
        //pembuatan object t dengan memanggil parameter dari consuktror transaksi dengan parameter
        //textTanggal, txtNamaBrg, txthargaBarang, txtJumlah, txtHargaTotal, txtBayar, dan txtKembalian
        //object n menambah data dari object t
        //lalu memmanggil method tampil untuk menampilkan semua yang telah di proses 
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txthargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaBarangActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void btnTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTglActionPerformed
        // TODO add your handling code here:
        //Membuat object calendar dari class Calendar dengan isi method getInstance pada class Calendar
        Calendar calendar = Calendar.getInstance();
        //Membuat format tanggal baru = Hari-Bulan-Tahun
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        //Merubah format tanggal pada method getTime() menjadi Hari-Bulan-Tahun
        String date = format.format(calendar.getTime());
        //Mengeset nilai txtPinjam dengan variabel date
        txtTanggal.setText(date);
        //Menambah 7 hari dari hari ini
        calendar.add(Calendar.DAY_OF_MONTH, 7);
        //Merubah format tanggal pada method getTime() menjadi Hari-Bulan-Tahun
        
    }//GEN-LAST:event_btnTglActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTgl;
    private javax.swing.JComboBox<String> comboPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHargaTotal;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNamaBrg;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txthargaBarang;
    // End of variables declaration//GEN-END:variables
}
